# Generated by Django 4.0.1 on 2022-02-01 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lineas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_final', models.DateTimeField()),
                ('estacion_final', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes_finalizados', to='lineas.estacion')),
                ('estacion_inicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes_iniciados', to='lineas.estacion')),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='lineas.pasajero')),
            ],
        ),
    ]
